[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
evm_version = 'london'
solc = '0.8.20'

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
